version : '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - '27017:27017'
    volumes:
      - ./backend/db/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend-container
    environment:
      - MONGO_URI=mongodb://root:rootpassword@mongodb-container:27017/movieRater?authSource=admin
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge